import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import axios from 'axios';
import { FileText, Download, Edit3, Loader2, CheckCircle } from 'lucide-react';
import jsPDF from 'jspdf'; // Run: npm install jspdf

const DocGen = ({ caseData }) => {
  const [suggestions, setSuggestions] = useState([]);
  const [selectedDoc, setSelectedDoc] = useState(null);
  const [docContent, setDocContent] = useState("");
  const [loading, setLoading] = useState(false);

  // Fetch suggestions when page loads
  useEffect(() => {
    const getSuggestions = async () => {
      try {
        const res = await axios.post('http://localhost:8000/documents/suggest', { case_data: caseData });
        setSuggestions(res.data.suggestions);
      } catch (e) { console.error("Failed to fetch suggestions"); }
    };
    if (caseData) getSuggestions();
  }, [caseData]);

  const handleGenerate = async (title) => {
    setSelectedDoc(title);
    setLoading(true);
    try {
      const res = await axios.post('http://localhost:8000/documents/generate', { 
        case_data: caseData, 
        selected_doc: title 
      });
      setDocContent(res.data.document_text);
    } catch (e) { alert("Generation failed"); }
    setLoading(false);
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    const margin = 10;
    const pageWidth = doc.internal.pageSize.width - (margin * 2);
    const lines = doc.splitTextToSize(docContent, pageWidth);
    doc.text(lines, margin, 20);
    doc.save(`${selectedDoc.replace(/\s+/g, '_')}.pdf`);
  };

  return (
    <div className="max-w-4xl mx-auto p-8">
      <h2 className="text-3xl font-bold text-lawzy-gold mb-2">Document Draftsman</h2>
      <p className="text-gray-400 mb-8">Select a document to generate based on your case details.</p>

      {/* 1. Suggestion Buttons */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-12">
        {suggestions.map((doc, i) => (
          <button
            key={i}
            onClick={() => handleGenerate(doc.title)}
            className={`p-4 rounded-xl border transition-all text-left ${
              selectedDoc === doc.title ? 'border-lawzy-gold bg-lawzy-gold/10' : 'border-gray-700 bg-lawzy-slate hover:border-gray-500'
            }`}
          >
            <FileText className="text-lawzy-gold mb-2" size={20} />
            <div className="font-bold text-sm">{doc.title}</div>
            <div className="text-[10px] text-gray-500 mt-1">{doc.description}</div>
          </button>
        ))}
      </div>

      {/* 2. Generation Area */}
      <AnimatePresence>
        {loading && (
          <motion.div 
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            className="flex flex-col items-center justify-center p-20 bg-lawzy-slate rounded-3xl border border-dashed border-lawzy-gold/30"
          >
            <Loader2 className="animate-spin text-lawzy-gold mb-4" size={40} />
            <p className="text-lawzy-gold font-mono animate-pulse uppercase tracking-widest text-xs">
              AI is drafting your {selectedDoc}...
            </p>
          </motion.div>
        )}

        {docContent && !loading && (
          <motion.div 
            initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }}
            className="bg-white text-black p-10 rounded shadow-2xl font-serif leading-relaxed relative"
          >
            <div className="absolute top-4 right-4 flex gap-2 no-print">
               <button onClick={downloadPDF} className="p-2 bg-blue-600 text-white rounded-full hover:bg-blue-700 shadow-lg">
                  <Download size={20} />
               </button>
            </div>
            
            {/* The Document View */}
            <div className="whitespace-pre-wrap text-sm border-t-4 border-black pt-8">
              {docContent}
            </div>

            <div className="mt-12 pt-8 border-t border-gray-200 text-[10px] text-gray-400 italic">
              Generated by Lawzy AI. Please review with a legal professional before signing.
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default DocGen;